EMAIL_EXISTS_ERROR_MESSAGE = 'This is email is already used by another user.'
EMAIL_NOT_EXISTS_ERROR_MESSAGE = 'Email not found in the system.'
INVALID_PASSWORD_ERROR_MESSAGE = 'Invalid password.'
USER_REGISTERED_SUCCESSFULLY_MESSAGE = 'You have successfully registered.'
USER_IS_NOT_ACTIVE_MESSAGE = 'This account account has been disabled. Contact site administrator.'
